export const URL_BACK_AUTHENTICATE = '/authenticate'
export const URL_BACK_GET_ALL_PRODUCT_IN_CART = '/getcart/'
export const URL_BACK_REGISTER = '/register'
export const URL_BACK_VERIFY_EMAIL_USER = '/confirm_register/'
export const URL_BACK_RESET_PASSWORD = '/reset-password'
export const URL_BACK_VALID_RESET_PASSWORD = '/valid-reset-password/'