export const URL_HOME = '/'
export const URL_LOGIN = '/login'
export const URL_REGISTER = '/register'
export const URL_ADMIN_HOME = '/admin'
export const URL_CART = '/cart/:id'
export const URL_VERIFY_USER_EMAIL = '/confirm/:confirmationCode'